// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/manage-indicators": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/manage-indicators" | "/profile" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./login/page.jsx": {
    id: "login/page";
    page: "/login";
  };
  "./manage-indicators/page.jsx": {
    id: "manage-indicators/page";
    page: "/manage-indicators";
  };
  "./profile/page.jsx": {
    id: "profile/page";
    page: "/profile";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "login/page": typeof import("./src/app/./login/page.jsx");
  "manage-indicators/page": typeof import("./src/app/./manage-indicators/page.jsx");
  "profile/page": typeof import("./src/app/./profile/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};